# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Drawer ordering (articulated object + irreversible precedence) for the reBot arm.

Pull a drawer open by its handle, then put a block inside. Two things here that the
pick-and-place task never asks for:

* **Articulated interaction.** The gripper has to follow a kinematic constraint it does not
  know, applying force along the drawer's slide axis and nowhere else. A policy that simply
  "wants" to move off that manifold stalls or rips off the handle.
* **Irreversible precedence.** The block cannot go in until the drawer is open, and the
  carry reward is *hard-gated* to zero until then -- there is no smooth distance gradient
  bridging the two stages, unlike carrying an object toward an always-open basket.

The handle is a 20 mm bar standing 22 mm off the drawer face so the fingers can straddle it
**side-on**; this arm has no top-down grasp below z = 0.19 m and could not reach over a lip
(docs/CHALLENGE_SUITE.md C1). The cabinet stands on a 45 mm plinth at x = 0.265, both of
which are forced by measurement rather than taste: the usable TCP band is x ~ 0.22..0.26 and
the gripper cannot be positioned below z = 44 mm at all, so at table height the handle would
have been permanently out of reach (``scripts/analysis/tcp_floor.py``). The drawer still
travels *toward* the robot as it opens, into easier space.

The asset is generated by ``scripts/challenge/author_drawer_usd.py``.
"""

import os
from dataclasses import MISSING

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import FrameTransformerCfg
from isaaclab.sensors.frame_transformer.frame_transformer_cfg import OffsetCfg
from isaaclab.sim.schemas.schemas_cfg import RigidBodyPropertiesCfg
from isaaclab.sim.spawners.from_files.from_files_cfg import GroundPlaneCfg, UsdFileCfg
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR
from isaaclab.utils.configclass import configclass
from isaaclab_physx.physics import PhysxCfg

from reBot_RL.assets import REBOT_ARM_CFG

from ..lift.rebot_lift_env_cfg import _BASE_LINK, _GRIPPER_CLOSE, _GRIPPER_END, _GRIPPER_OPEN, _START_POSE
from . import mdp

FINGER_STIFFNESS = 2000.0
FINGER_DAMPING = 40.0

# this file is .../reBot_RL/tasks/manager_based/challenge/, and the data dir is a sibling
# of the reBot_RL package, so four levels up (same convention as assets/rebot_arm.py)
_DATA = os.path.abspath(
    os.path.join(os.path.dirname(__file__), *([".."] * 4), "data", "drawer", "drawer.usda")
)

DRAWER_CFG = SceneEntityCfg("drawer")


@configclass
class DrawerSceneCfg(InteractiveSceneCfg):
    """Table, arm, the cabinet articulation, and the block to be stowed."""

    robot: ArticulationCfg = MISSING
    ee_frame: FrameTransformerCfg = MISSING

    drawer = ArticulationCfg(
        prim_path="{ENV_REGEX_NS}/Cabinet",
        spawn=sim_utils.UsdFileCfg(
            usd_path=_DATA,
            rigid_props=RigidBodyPropertiesCfg(
                disable_gravity=False,
                max_depenetration_velocity=1.0,
                solver_position_iteration_count=16,
                solver_velocity_iteration_count=1,
            ),
            articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                enabled_self_collisions=False,
                solver_position_iteration_count=16,
                solver_velocity_iteration_count=1,
            ),
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            # standing on a plinth: the handle would otherwise sit at z = 26 mm, below the
            # measured 44 mm TCP floor, and no policy could ever reach it
            pos=(*mdp.CABINET_XY, mdp.CABINET_Z),
            joint_pos={"DrawerJoint": 0.0},  # starts shut -- the precedence gate
        ),
        actuators={
            # zero stiffness: the drawer must be *dragged*, not driven to a setpoint.
            # A little damping keeps it where it is put instead of coasting.
            "drawer": ImplicitActuatorCfg(
                joint_names_expr=["DrawerJoint"], stiffness=0.0, damping=8.0, effort_limit=40.0
            ),
        },
    )

    # what the cabinet stands on. Purely structural, but it has to be there or the cabinet
    # floats and the scene reads as broken.
    plinth = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Plinth",
        init_state=AssetBaseCfg.InitialStateCfg(pos=(*mdp.CABINET_XY, mdp.CABINET_Z / 2)),
        spawn=sim_utils.CuboidCfg(
            size=(0.090, 0.130, mdp.CABINET_Z),
            collision_props=sim_utils.CollisionPropertiesCfg(),
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.28, 0.30, 0.34)),
        ),
    )

    block = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/Block",
        # spawns to the robot's right, clear of the drawer's travel path
        init_state=RigidObjectCfg.InitialStateCfg(pos=[0.235, -0.135, 0.025], rot=[0.0, 0.0, 0.0, 1.0]),
        spawn=sim_utils.CuboidCfg(
            size=(0.030, 0.030, 0.050),
            rigid_props=RigidBodyPropertiesCfg(
                solver_position_iteration_count=16,
                solver_velocity_iteration_count=1,
                max_depenetration_velocity=1.0,
                disable_gravity=False,
            ),
            mass_props=sim_utils.MassPropertiesCfg(mass=0.04),
            collision_props=sim_utils.CollisionPropertiesCfg(contact_offset=0.002, rest_offset=0.0),
            physics_material=sim_utils.RigidBodyMaterialCfg(
                static_friction=1.0, dynamic_friction=0.85, restitution=0.0
            ),
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.20, 0.60, 0.35)),
        ),
    )

    table = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Table",
        init_state=AssetBaseCfg.InitialStateCfg(pos=[0.5, 0, 0], rot=[0, 0, 0.707, 0.707]),
        spawn=UsdFileCfg(usd_path=f"{ISAAC_NUCLEUS_DIR}/Props/Mounts/SeattleLabTable/table_instanceable.usd"),
    )
    plane = AssetBaseCfg(
        prim_path="/World/GroundPlane",
        init_state=AssetBaseCfg.InitialStateCfg(pos=[0, 0, -1.05]),
        spawn=GroundPlaneCfg(),
    )
    light = AssetBaseCfg(
        prim_path="/World/light",
        spawn=sim_utils.DomeLightCfg(color=(0.75, 0.75, 0.75), intensity=3000.0),
    )


@configclass
class ActionsCfg:
    arm_action = mdp.JointPositionActionCfg(
        asset_name="robot", joint_names=["joint[1-6]"], scale=0.5, use_default_offset=True
    )
    gripper_action = mdp.BinaryJointPositionActionCfg(
        asset_name="robot",
        joint_names=["joint_left", "joint_right"],
        open_command_expr={"joint_left": _GRIPPER_OPEN, "joint_right": _GRIPPER_OPEN},
        close_command_expr={"joint_left": _GRIPPER_CLOSE, "joint_right": _GRIPPER_CLOSE},
    )


@configclass
class ObservationsCfg:
    """Privileged state, 33-D."""

    @configclass
    class PolicyCfg(ObsGroup):
        joint_pos = ObsTerm(func=mdp.joint_pos_rel)                                  # 8
        joint_vel = ObsTerm(func=mdp.joint_vel_rel)                                  # 8
        block_pose = ObsTerm(func=mdp.block_pose_in_root)                            # 7
        # (opening fraction, is_open, block_in_drawer) -- the stage state is observable,
        # so the policy does not have to infer which phase of the task it is in
        drawer_state = ObsTerm(func=mdp.drawer_obs, params={"asset_cfg": DRAWER_CFG})  # 3
        actions = ObsTerm(func=mdp.last_action)                                      # 7

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = True

    policy: PolicyCfg = PolicyCfg()


@configclass
class RewardsCfg:
    # stage 1: open the drawer
    reach_handle = RewTerm(
        func=mdp.reach_handle, weight=2.0,
        params={"std": 0.10, "ee_frame_cfg": SceneEntityCfg("ee_frame"), "asset_cfg": DRAWER_CFG},
    )
    opening = RewTerm(func=mdp.opening_progress, weight=25.0, params={"asset_cfg": DRAWER_CFG})

    # stage 2: only reachable once stage 1 is done -- these are zero until then
    reach_block = RewTerm(
        func=mdp.reach_block, weight=1.5,
        params={"std": 0.12, "ee_frame_cfg": SceneEntityCfg("ee_frame")},
    )
    lifting = RewTerm(
        func=mdp.block_lifted, weight=8.0,
        # the cavity floor is at 57 mm, so the block has to clear that to go in
        params={"minimal_height": 0.070, "ee_max_dist": 0.08,
                "ee_frame_cfg": SceneEntityCfg("ee_frame")},
    )
    carrying = RewTerm(func=mdp.block_to_drawer, weight=15.0,
                       params={"std": 0.12, "asset_cfg": DRAWER_CFG})
    success = RewTerm(func=mdp.drawer_success, weight=60.0, params={"asset_cfg": DRAWER_CFG})

    dropping_penalty = RewTerm(
        func=mdp.is_terminated_term, weight=-30.0, params={"term_keys": "block_dropped"}
    )
    action_rate = RewTerm(func=mdp.action_rate_l2, weight=-2e-2)
    joint_vel = RewTerm(func=mdp.joint_vel_l2, weight=-5e-3, params={"asset_cfg": SceneEntityCfg("robot")})


@configclass
class TerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)
    block_dropped = DoneTerm(func=mdp.block_dropped, params={"minimum_height": -0.05})


@configclass
class EventCfg:
    reset_all = EventTerm(func=mdp.reset_scene_to_default, mode="reset")
    reset_block = EventTerm(
        func=mdp.reset_root_state_uniform, mode="reset",
        params={"pose_range": {"x": (-0.02, 0.02), "y": (-0.03, 0.03), "yaw": (-0.4, 0.4)},
                "velocity_range": {}, "asset_cfg": SceneEntityCfg("block")},
    )
    # the drawer always starts shut: a partly-open start would leak away the precedence
    # constraint that is the point of the task
    block_material = EventTerm(
        func=mdp.randomize_rigid_body_material, mode="startup",
        params={"asset_cfg": SceneEntityCfg("block"),
                "static_friction_range": (0.9, 1.1), "dynamic_friction_range": (0.75, 0.95),
                "restitution_range": (0.0, 0.0), "num_buckets": 16},
    )


@configclass
class RebotDrawerOrderEnvCfg(ManagerBasedRLEnvCfg):
    """Open a drawer, then stow a block in it. Order is enforced by geometry."""

    scene: DrawerSceneCfg = DrawerSceneCfg(num_envs=1024, env_spacing=2.5)
    observations: ObservationsCfg = ObservationsCfg()
    actions: ActionsCfg = ActionsCfg()
    rewards: RewardsCfg = RewardsCfg()
    terminations: TerminationsCfg = TerminationsCfg()
    events: EventCfg = EventCfg()

    def __post_init__(self):
        self.scene.robot = REBOT_ARM_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        self.scene.robot.init_state.joint_pos = dict(_START_POSE)
        self.scene.robot.actuators = {
            "arm": ImplicitActuatorCfg(joint_names_expr=["joint[1-6]"], stiffness=None, damping=None),
            "fingers": ImplicitActuatorCfg(
                joint_names_expr=["joint_left", "joint_right"],
                stiffness=FINGER_STIFFNESS, damping=FINGER_DAMPING,
            ),
        }
        self.scene.ee_frame = FrameTransformerCfg(
            prim_path=f"{{ENV_REGEX_NS}}/Robot/{_BASE_LINK}",
            debug_vis=False,
            target_frames=[
                FrameTransformerCfg.FrameCfg(
                    prim_path=f"{{ENV_REGEX_NS}}/Robot/{_GRIPPER_END}",
                    name="end_effector",
                    # measured TCP, not the -0.075 inherited from the lift task -- see
                    # mdp/common.TCP_OFFSET
                    offset=OffsetCfg(pos=mdp.TCP_OFFSET),
                )
            ],
        )
        self.decimation = 8
        self.episode_length_s = 16.0  # two hard stages in sequence
        self.sim.dt = 1.0 / 400.0
        self.sim.render_interval = self.decimation
        self.sim.physics = PhysxCfg(
            bounce_threshold_velocity=0.01,
            gpu_found_lost_aggregate_pairs_capacity=1024 * 1024 * 4,
            gpu_total_aggregate_pairs_capacity=128 * 1024,
            friction_correlation_distance=0.00625,
            gpu_max_rigid_patch_count=2**19,
        )


@configclass
class RebotDrawerOrderEnvCfg_PLAY(RebotDrawerOrderEnvCfg):
    def __post_init__(self):
        super().__post_init__()
        self.scene.num_envs = 16
        self.scene.env_spacing = 2.0
